version: "3.7"
services:

  user_service:
    build:
      context: ./user
      dockerfile: Dockerfile
    restart: always
    networks:
      - shared-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://DS2024_1_user_db:3306/DS2024_1_user_db?allowPublicKeyRetrieval=true
    depends_on:
      - DS2024_1_user_db
    volumes:
      - ~/.m2:/root/.m2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user_service.rule=Host(`user.localhost`)"
      - "traefik.http.services.user_service.loadbalancer.server.port=8080"
    deploy:
      replicas: 2

  device_service:
    build:
      context: ./device
      dockerfile: Dockerfile
    restart: always
    networks:
      - shared-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://DS2024_1_device_db:3306/DS2024_1_device_db?allowPublicKeyRetrieval=true
#      - SPRING_RABBITMQ_HOST=kangaroo.rmq.cloudamqp.com
#      - SPRING_RABBITMQ_PORT=5671
#      - SPRING_RABBITMQ_USERNAME=lnyamrif
#      - SPRING_RABBITMQ_PASSWORD=CYa3_9jqczcawKY9B4Qoa5iQNnz6z_Cb
#      - SPRING_RABBITMQ_VIRTUALHOST=lnyamrif
#      - SPRING_RABBITMQ_SSL_ENABLED=true
#      - SPRING_RABBITMQ_SSL_VERIFY_HOSTNAME=true
#      - SPRING_RABBITMQ_SSL_ALGORITHM=TLSv1.2
#      - SPRING_RABBITMQ_QUEUE=ds_project
    depends_on:
      - DS2024_1_device_db
    volumes:
      - ~/.m2:/root/.m2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.device_service.rule=Host(`device.localhost`)"
      - "traefik.http.services.device_service.loadbalancer.server.port=8081"
    deploy:
      replicas: 2

  monitoring_service:
    build:
      context: ./monitoring
      dockerfile: Dockerfile
    restart: always
    networks:
      - shared-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://DS2024_2_monitoring_db:3306/DS2024_2_monitoring_db?allowPublicKeyRetrieval=true
    depends_on:
      - DS2024_2_monitoring_db
    volumes:
      - ~/.m2:/root/.m2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.monitoring_service.rule=Host(`monitoring.localhost`)"
      - "traefik.http.services.monitoring_service.loadbalancer.server.port=8082"

  chat_service:
    build:
      context: ./chat
      dockerfile: Dockerfile
    restart: always
    networks:
      - shared-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://DS2024_3_chat:3306/DS2024_3_chat?allowPublicKeyRetrieval=true
    depends_on:
      - DS2024_3_chat
    volumes:
      - ~/.m2:/root/.m2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chat_service.rule=Host(`chat.localhost`)"
      - "traefik.http.services.chat_service.loadbalancer.server.port=8083"



  reverse_proxy:
    image: traefik:v3.2
    command:
      - --api.insecure=true
      - --api.dashboard=true  # Enable dashboard endpoints
      - --providers.docker
      - --entrypoints.web.address=:80
#      - --entrypoints.web.forwardedheaders.insecure=true
#      - --entrypoints.web.websocket=true   # Enable WebSocket support
    ports:
      - "80:80"
      - "8080:8080"    # Traefik dashboard port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - shared-network

  DS2024_1_user_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3307:3306
    networks:
      - shared-network
    environment:
      MYSQL_DATABASE: DS2024_1_user_db
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: rootpass

  DS2024_1_device_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3308:3306
    networks:
      - shared-network
    environment:
      MYSQL_DATABASE: DS2024_1_device_db
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: rootpass

  DS2024_2_monitoring_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3309:3306
    networks:
      - shared-network
    environment:
      MYSQL_DATABASE: DS2024_2_monitoring_db
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: rootpass

  DS2024_3_chat:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3310:3306
    networks:
      - shared-network
    environment:
      MYSQL_DATABASE: DS2024_3_chat
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: rootpass

networks:
  shared-network:
    driver: bridge
